name: smart_store_linux
description: AI-powered video analytics and store monitoring system.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.1.1
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  equatable: ^2.0.5
  get_it: ^8.0.2
  # File system
  path_provider: ^2.1.1
  # (Optional) For decoding images to show on screen
  # Video dependencies
  # fvp: ^0.35.1 (Removed)
  # video_player: ^2.8.1 (Removed)

  # Utilities
  shared_preferences: ^2.2.0
  uuid: ^4.0.0
  path: ^1.8.0
  
  # Desktop
  window_manager: ^0.5.1
  
  # Icons
  cupertino_icons: ^1.0.2
  ffi: ^2.1.4
  native_onnx:
    path: ./packages/native_onnx
  native_rknn:
    path: ./packages/native_rknn
  file_picker: ^10.3.8
  permission_handler: ^12.0.1
  json_annotation: ^4.10.0
flutter:
  uses-material-design: true
dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.11.1
  json_serializable: ^6.12.0
