name: smart_store_linux
description: FFmpeg based AI counter
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  # State Management
  provider: ^6.1.1
  # File system
  path_provider: ^2.1.1
  # (Optional) For decoding images to show on screen
  image: ^4.1.3 
  
  # UI & Media
  google_fonts: ^6.1.0
  
  # Video dependencies
  fvp: ^0.35.1
  bitmap: ^0.2.0
  video_player: ^2.8.1
  
  # Utilities
  shared_preferences: ^2.2.0
  uuid: ^4.0.0
  path: ^1.8.0
  
  # Desktop
  window_manager: ^0.5.1
  
  # Icons
  cupertino_icons: ^1.0.2
  ffi: ^2.1.4
  native_onnx:
    path: ./packages/native_onnx
  file_picker: ^10.3.7

flutter:
  uses-material-design: true
  assets:
    - assets/