org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError

# 2. Disable parallel and caching temporarily 
# This ensures a "clean" path for R8 and prevents race conditions
org.gradle.parallel=false
org.gradle.caching=false

# 3. Keep these as they are required for Flutter
android.useAndroidX=true
android.enableJetifier=true