org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx3G -XX:+UseParallelGC -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF-8

# Linux-specific speed up: Don't re-scan the filesystem constantly
org.gradle.vfs.watch=true
android.enableJetifier=true
android.useAndroidX=true